# Generated by Django 4.1.7 on 2023-06-18 12:59

import User.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_appuser_groups_alter_appuser_user_permissions'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='appuser',
            managers=[
                ('objects', User.models.AppUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='appuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
