# Generated by Django 4.1.7 on 2023-06-18 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_appuser_managers_appuser_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='username',
        ),
    ]
